version: '3'

services:
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    logging:
      options:
        max-size: 10m
        max-file: "3"
  # mysql:
  #   image: mysql:5.6
  #   container_name: airflow_db
  #   environment:
  #       - MYSQL_ROOT_PASSWORD=root
  #       - MYSQL_DATABASE=airflow
  #       - MYSQL_USER=airflow
  #       - MYSQL_PASSWORD=airflow
  #   command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  webserver:
    build: ./dockerfiles
    restart: always
    depends_on:
      - postgres
      # - mysql
    environment:
      - LOAD_EX=n
      - EXECUTOR=Local
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./logs:/usr/local/airflow/logs
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
